name: Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: rubygems.org
    steps:
      - uses: actions/checkout@v5
        with:
          # See: https://github.com/actions/checkout/issues/1467#issuecomment-2764532031
          fetch-depth: 1
          fetch-tags: true
          ref: ${{ github.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      - uses: rubygems/release-gem@a25424ba2ba8b387abc8ef40807c2c85b96cbe32
