name: Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: rubygems.org
    steps:
      - uses: actions/checkout@v4
        with:
          # See: https://github.com/actions/checkout/issues/1467#issuecomment-2764532031
          fetch-depth: 1
          fetch-tags: true
          ref: ${{ github.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      - uses: rubygems/configure-rubygems-credentials@e3f5097339179e0d4c7321ab44209e7e02446746
        with:
          role-to-assume: ${{ secrets.RUBYGEMS_ORG_OCID }}

      - run: bundle exec rake release

      - name: Wait for release to propagate
        run: |
          gem install rubygems-await
          gem_tuple="$(ruby -rbundler/setup -rbundler -e '
              spec = Bundler.definition.specs.find {|s| s.name == ARGV[0] }
              raise "No spec for #{ARGV[0]}" unless spec
              print [spec.name, spec.version, spec.platform].join(":")
            ' "swagger_ui_standalone")"
          gem await "${gem_tuple}"
